name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: "ubuntu"
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 400 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
          cd mock-interview
          git pull origin main
          
          cd server
          npm install
          npm run build
          pm2 restart jobsforce-backend

          cd ../client
          npm install
          npm run build
          sudo mv dist /var/www/jobsforce
          sudo systemctl restart nginx
        EOF
